### ISSUE TITLE
stdout output on every log line

### ISSUE THREAD

**Issue by machadolab** [logdna/ruby#1]
https://github.com/logdna/ruby/blob/830fa833fcb651fd69fc60e4efb91b94319db711/lib/logdna/client.rb#L145

Library code should not be directly calling puts, especially in a non-failure scenario.

**Comment by respectus** [comment]
Hi @machadolab,

Appreciate you catching this line, definitely unnecessary and has been removed from version 1.1.1. Please do let me know if you experience any issues with the gem. I'm going to mark this one as closed since it is a trivial issue that has been resolved. Thanks for helping us improve the gem!
